"""add journey table

Revision ID: 64517299a5e2
Revises: c8443d1091d1
Create Date: 2026-02-02 12:31:09.153776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64517299a5e2'
down_revision = 'c8443d1091d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journey')
    # ### end Alembic commands ###
