"""empty message

Revision ID: a3983ab1f617
Revises: df46245e1686
Create Date: 2026-03-21 09:19:51.662051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3983ab1f617'
down_revision = 'df46245e1686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProfileImg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('banner_picture_url', sa.Text(), nullable=True))

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloud_url', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('cloud_url')

    with op.batch_alter_table('ProfileImg', schema=None) as batch_op:
        batch_op.drop_column('banner_picture_url')
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
